{% set name = "h3" %}
{% set version = "3.7.3" %}

package:
  name: {{ name|lower }}-py
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 75214450b89e5204d77700e01cf2d41a02d7cbfe9b9ca925727c52e18f91072e

build:
  number: 4
  skip: true  # [python_impl == 'pypy']
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make                  # [unix]
  host:
    - python
    - pip
    - scikit-build
    - cython
  run:
    - python
    - numpy

test:
  imports:
    - h3

about:
  home: https://github.com/uber/h3-py.git
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Python bindings for H3, a hierarchical hexagonal geospatial indexing system developed by Uber Technologies
  dev_url: https://github.com/uber/h3-py.git

extra:
  recipe-maintainers:
    - mxr-conda
    - bubblyorca
    - geoHeil
